services:
  rota_certa_backend:
    build:
      context: ./api
    container_name: rota_certa_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://docker:docker@api-rotacerta-pg:5432/api-rotacerta"
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5555:5555"
    depends_on:
      - api-rotacerta-pg
    command: ["sh", "-c", "./wait-for-it.sh api-rotacerta-pg:5432 -- npx prisma migrate deploy && npm run seed && npm start"]

  rota_certa_frontend:
    build:
      context: ./front
    container_name: rota_certa_frontend
    restart: unless-stopped
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8080"
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - rota_certa_backend

  api-rotacerta-pg:
    image: postgres:latest
    container_name: api-rotacerta-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api-rotacerta
    ports:
      - "5432:5432"